### ISSUE TITLE
2 simplest projects Vue3 Typescript Vite integration 

### ISSUE THREAD

**Issue by clabnet** [micro-lc/micro-lc#707]
I have try to find integration of micro-lc with Vue projects but I don't found any.

So I have created two hello world VUE3 TYPESCRIPT VITE projects and make the base configuration with micro-lc.
[https://github.com/clabnet/microlc-vue](https://github.com/clabnet/microlc-vue)

The actual result is the start of micro-lc page with a 400 error, and 500 errors when activating MFE1 or MFE2.

Do you like please support me to configure correctly for run the two simple projects as "parcel" mode ?

Thank you very mutch.

**Comment by epessina** [comment]
Hi @clabnet, thanks for your interest in micro-lc! 

We’re taking a look at your issue and we’ll be back to you in a few days

**Comment by clabnet** [comment]
Hi @epessina , do you have see this recent PR https://github.com/micro-lc/micro-lc/pull/712 ? 
Can be interesting for my request.  
I'm still waiting your considerations, when you have time for this. 
Thank's

**Comment by clabnet** [comment]
First, thank you @amountainram @epessina for the the fastest assistance and support. 
I'll try your solution as soon, (although it doesn't seem to be simple to implement).

**Comment by amountainram** [comment]
sure thing. 
on your first screenshot you've got 404 on http://localhost:8000/vue-template/.
how are you serving the vue MF?
may you pls copy/paste your current `vite.config.ts` file for `vue-template` MF?

**Comment by clabnet** [comment]
All my code ir on the repo https://github.com/clabnet/microlc-vue.

```
import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import microLc from './plugins/vite-plugin-micro-lc'
// https://vitejs.dev/config/
export default defineConfig({
  base: '/',
  build: {
    minify: false
  },
  plugins: [
    vue(),
    vueJsx(),
    microLc('vue3'),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})

```

**Comment by amountainram** [comment]
The base option of the vite.config.js must match the position where statics will be served. In your case /vue-template/. Refer pls to the documentation on the vue template at build section. This I reckon would solve the first 404 issue

**Comment by amountainram** [comment]
beside.. the `vue-template` uses `@micro-lc/orchestrator` for types only, hence `peerDependencies` are not a problem.

**Comment by clabnet** [comment]
@amountainram 

> How are you serving the template bundle? Cuz I can clearly tell that micro-lc is being served on port 8000.. are you employing a reverse proxy?

You find detailed instructions into README into my repo. https://github.com/clabnet/microlc-vue
I have used `static` npm package as you suggested into your site,  To start all project I run two command into 2 terminal :
```
1. static --port 8000        < to start web server 
2. pnpm -r dev                 < to start recursively all tasks "dev". This command open two websites, on port 3010 and 3020. 
```

So, i have updated the `base` on vite .config.ts respectively :
-   base: '/vue3-template/',  for vue3-template 
-   base: '/mfe1/',   for mfe1

For mfe1 is there this error:
![image](https://github.com/micro-lc/micro-lc/assets/6067610/bd8594a5-eeca-421d-8032-c016842c3f01)

For vue3-template : 
![image](https://github.com/micro-lc/micro-lc/assets/6067610/65c17d7d-7a66-474a-a326-9734e89ffc44)

For now you can omit to see mfe2, we will make it work later.

**My focus is to run together my mfe1 and your vue3-template projects** to see the differences and learn to configure micro-lc onto my context.  

If you could take some time and clone my repo https://github.com/clabnet/microlc-vue maybe it would be easier to figure out what errors I'm running into.

Since mfe1 and mfe2 are basics hello-world VUE3 VITE projects  it might be useful as a basis for other vue developers and add its to your integration examples.

Thank's for your support.

**Comment by amountainram** [comment]
Ive attempted to start the project but pnpm is not installing workspaces. Would you mind to update the readme providing steps to install it from scratch? There's a reference to a "dev" script which ain't there for instance

**Comment by clabnet** [comment]
Hi @amountainram, 
`pnpm install`  fail  when adding  "@micro-lc/orchestrator": "^2.1.0"  as dependencies of mfe1 and/or vue3-template with this error :   
```
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/ajv-format: Not Found - 404
This error happened while installing a direct dependency of D:\_PROJECTS\POMINI\labs\microlc-vue\packages\vue3-template
ajv-format is not in the npm registry, or you have no permission to fetch it.
An authorization header was used: Bearer npm_[hidden]
```
I don't know why is required the orchestrator, because the script is already present into index.html 
```
<script type="module" src="https://cdn.jsdelivr.net/npm/@micro-lc/orchestrator@latest/dist/micro-lc.production.js"></script>
```
When removed the dependencies the `pnpm i` proceed regularly installing the dependencies "on cascade" into each app into packages folder. I updated my repo, you can pull my latest changes from main branch.

If you say that     "@micro-lc/orchestrator": "^2.1.0",   is required also as dependencies, in that case I can trye using the 'yarn' as PM, as you use. I think PNPM is + modern and efficiently respect yarn. But I can be wrong.

**Comment by amountainram** [comment]
Hi Claudio,
we are figuring out a good time for us to schedule a live session.

In the meanwhile, I managed to start your repo:
1. in the `config.yaml` file you reference the entry point of `vue3-template` as `/vue3-template/` -> this can be achieved only using a reverse proxy setup that redirects calls to `/vue3-template/` to the webserver is actually serving the `vue3-template` (in your case with `vite` it'll be `https://localhost:4173/`.
2. bundling with vite does not allow testing the application in `micro-lc` in `dev` mode -> meaning that you must build it and then refer to the bundled static files as per point 1.
3. also due to `vite` and the `vue` plugin, in the current setup, `vue3-template` is bundles as an ESM script which is currently not supported by [`micro-lc`](https://micro-lc.io/docs/guides/applications/parcels) -> to mitigate this lack of support we wrapped a qiankun plugin for vite which is included in the [`micro-lc/vue-template`](https://github.com/micro-lc/vue3-template) repo under `/plugins/vite-plugin-micro-lc.ts`. Due to this fact the `vue3-template` app must be served via reverse proxy, as per point 1 in order to mantain the same `origin` of the `micro-lc` web page.
4. As mentioned in previous messages, `@micro-lc/orchestrator` provides to `vue3-template` only `types` thus is not required and can be removed from deps by commenting the relative interface

```typescript
export interface MicrolcProps extends QiankunProps {
  container?: HTMLElement
  formKind?: string
  // microlcApi?: MicrolcApi<BaseExtension>
}
```

**Comment by clabnet** [comment]
Sorry but there are things unclear for me. (points 2, 3, 4). 
I cannot proceed as is with this support level.

**Comment by akelity** [comment]
Hi @clabnet,
My name is Michel Murabito, a Developer Advocate at Mia-Platform, and I would like to highlight a crucial aspect of our work with open-source projects, particularly regarding micro-lc. 

As you likely know, support in these contexts is provided on a "best effort" basis. This means that, although we put forth our utmost effort, our time and resources are limited. Our team is highly interested in providing assistance and ensuring that users like you can make the most out of micro-lc. However, it's important to understand that given the nature of our work, assistance cannot always be immediate.
When users open an issue or make a request, they should be aware that the resolution might take some time. This is due to the need to balance our commitment among various projects and requests. Having said this, we understand that there may be situations where immediate support is necessary. For these cases, we offer a dedicated professional service that can ensure a quick response and intervention.

We hope this information is helpful, and we ask for your understanding in managing these dynamics. We remain at your disposal for any further questions or clarifications.
